# Generated by Django 4.2.8 on 2026-09-01 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CD', 'CD'), ('DVD', 'DVD')], max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('artista_diretor', models.CharField(max_length=200)),
                ('codigo_barras', models.CharField(max_length=20, unique=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('gravadora_distribuidora', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('estado_conservacao', models.CharField(choices=[('novo', 'Novo'), ('excelente', 'Excelente'), ('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim')], default='bom', max_length=20)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('vendido', 'Vendido')], default='disponivel', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acervo.categoria')),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Itens',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
