# Generated by Django 5.2.17 on 2026-09-13 00:41

import acervo.validators
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_produto_exemplar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplar',
            name='codigo_interno',
            field=models.CharField(max_length=40, unique=True, validators=[acervo.validators.validar_codigo]),
        ),
        migrations.AlterField(
            model_name='exemplar',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ano',
            field=models.IntegerField(blank=True, null=True, validators=[acervo.validators.validar_ano]),
        ),
        migrations.AddConstraint(
            model_name='exemplar',
            constraint=models.CheckConstraint(condition=models.Q(('preco__gte', 0), ('preco__isnull', True), _connector='OR'), name='exemplar_preco_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('ano__gte', 1), ('ano__isnull', True), _connector='OR'), name='produto_ano_positivo'),
        ),
    ]
