# Generated by Django 5.2.17 on 2026-09-13 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_produto_exemplar'),
        ('movimentacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'ordering': ['-data', '-pk'], 'verbose_name_plural': 'Movimentações'},
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='anterior',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='novo',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='acervo.exemplar'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('cadastro', 'Cadastro legado'), ('entrada', 'Entrada'), ('edicao', 'Edição'), ('alteracao_preco', 'Alteração de preço'), ('mudanca_localizacao', 'Mudança de localização'), ('reserva', 'Reserva'), ('cancelamento_reserva', 'Cancelamento de reserva'), ('venda', 'Venda'), ('cancelamento', 'Cancelamento'), ('alteracao_status', 'Alteração de status')], max_length=40),
        ),
    ]
