# Generated by Django 4.2.8 on 2026-09-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('proprietario', 'Proprietário'), ('administrador', 'Administrador'), ('funcionario', 'Funcionário')], default='funcionario', max_length=20),
        ),
    ]
