# Generated by Django 5.2.17 on 2026-09-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteAPI',
            fields=[
                ('nome', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('ultima', models.DateTimeField(null=True)),
            ],
        ),
    ]
