# Generated by Django 5.2.17 on 2026-09-13 00:51

import acervo.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmeReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('imdb_id', models.CharField(blank=True, db_index=True, max_length=30, validators=[django.core.validators.RegexValidator('^tt[0-9]+$')])),
                ('titulo', models.CharField(db_index=True, max_length=300)),
                ('titulo_original', models.CharField(db_index=True, max_length=300)),
                ('ano', models.IntegerField(blank=True, db_index=True, null=True, validators=[acervo.validators.validar_ano])),
                ('descricao', models.TextField(blank=True)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('origem', models.CharField(default='Kaggle:rounakbanik/the-movies-dataset', max_length=100)),
            ],
        ),
    ]
