# Generated by Django 5.2.17 on 2026-09-29 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0002_filmereferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmereferencia',
            name='diretor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='filmereferencia',
            name='ean',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('\\A(?:[0-9]{8}|[0-9]{12}|[0-9]{13})\\Z', 'Informe EAN/UPC com 8, 12 ou 13 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='filmereferencia',
            name='origem',
            field=models.CharField(default='Base de DVDs do grupo', max_length=100),
        ),
        migrations.AlterField(
            model_name='filmereferencia',
            name='tmdb_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
